.TH "Junk" 3 "19 Mar 2007" "Battleship" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Junk \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Josh 
.RE
.PP

.PP
.SH "Member Function Documentation"
.PP 
.SS "static void Junk::main (String[] args)\fC [inline, static]\fP"
.PP
\fBParameters:\fP
.RS 4
\fIargs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Battleship from the source code.
